services:
  # Personal website with mini tools
  website:
    build: ./website
    environment:
      - NODE_ENV=development
    depends_on:
      - n8n

  # n8n workflow automation
  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

  # Nginx reverse proxy (local development)
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "5678:5678"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
    depends_on:
      - website
      - n8n
    restart: unless-stopped

volumes:
  n8n_data:
